apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appointment-service.name" . }}-deploy
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  
  selector:
    matchLabels:
      {{- include "appointment-service.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "appointment-service.labels" . | nindent 8 }}

    spec:
      containers:
      - name: {{ include "appointment-service.name" . }}-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: {{ .Values.service.ports.http.name }}
          containerPort: {{ .Values.service.ports.http.num }}
        - name: {{ .Values.service.ports.grpc.name }}
          containerPort: {{ .Values.service.ports.grpc.num }}