apiVersion: v1
kind: Service
metadata:
  name: {{ include "appointment-service.svcname" . }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "appointment-service.selectorLabels" . | nindent 4 }}
  
  ports:
  - name: {{ .Values.service.ports.grpc.name }}
    port: {{ .Values.service.ports.grpc.num }}
    targetPort: {{ .Values.service.ports.grpc.name }}
  - name: {{ .Values.service.ports.http.name }}
    port: {{ .Values.service.ports.http.num }}
    targetPort: {{ .Values.service.ports.http.name }}