apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "billing-service.appname" . }}
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "billing-service.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "billing-service.labels" . | nindent 8 }}

    spec:
      containers:
      - name: {{ include "billing-service.appname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: {{ .Values.service.ports.http.name }}
          containerPort: {{ .Values.service.ports.http.num }}
        - name: {{ .Values.service.ports.grpc.name }}
          containerPort: {{ .Values.service.ports.grpc.num }}