apiVersion: v1
kind: Service
metadata:
  name: {{ include "billing-service.name" . }}
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "billing-service.selectorLabels" . | nindent 4 }}

  ports:
  - name: {{ .Values.service.ports.grpc.name }}
    port: {{ .Values.service.ports.grpc.num }}
    targetPort: {{ .Values.service.ports.grpc.name }}
  - name: {{ .Values.service.ports.http.name }}
    port: {{ .Values.service.ports.http.num }}
    targetPort: {{ .Values.service.ports.http.name }}