apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service-deploy
spec:
  template:
    spec:
      containers:
        - name: billing-service-app
          image: somnathbm/hospital-hms-billing-service:dev-sha-bf1a497573969f5b8b59787a8e3e0b3f1088ae21