apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../../base/billing

patches:
  - path: billing-patch.yaml

# helmCharts:
#   - name: billing-service
#     valuesFile: billing-values.yaml
