apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - namespace.yaml

# patches:
#   - path: billing-patch.yaml

helmCharts:
  - name: billing-service
    repo: https://somnathbm.github.io/hospital-hms-infra/charts/
    version: 0.1.0
    releaseName: billing-release
    valuesFile: ./billing-values.yaml
