apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital-hms-ingress
  namespace: hospital-dev

spec:
  rules:
  - http:
      paths:
      - path: /api/v1/opd-svc
        pathType: Prefix
        backend:
          service: