apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: appointment-service
    version: 0.1.0
    releaseName: appointment-release
    valuesFile: values.yaml