apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deploy
spec:
  template:
    spec:
      containers:
        - name: appointment-service-app
          image: somnathbm/hospital-hms-appointment-service:dev-sha-e52636b6e0a141c299609328f4d7d58546ab45e9