apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../../base/appointment

patches:
  - path: appointment-patch.yaml

# helmCharts:
#   - name: appointment-service
#     valuesFile: appointment-values.yaml
