apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../../../base

patches:
  - path: appointment-patch.yaml

# helmCharts:
#   - name: billing-service
#     valuesFile: billing-values.yaml
#   - name: appointment-service
#     valuesFile: appointment-values.yaml
#   - name: opd-service
#     valuesFile: opd-values.yaml
