apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hospital-hms-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2a.medium
    desiredCapacity: 1

  - name: ng-2
    instanceType: t2a.medium
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes:
      - "audit"
    logRetentionInDays: 7