apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hospital-hms-eks5
  region: us-east-1

managedNodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 1

  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes:
      - "audit"
    logRetentionInDays: 7