apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hospital-hms-gateway
  namespace: hospital-hms
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
  - name: hospital-hms-listeners
    port: 80
    protocol: HTTP
    allowedRoutes:
      kinds:
      - kind: HTTPRoute