apiVersion: apps/v1
kind: Deployment
metadata:
  name: opd-service-deploy
spec:
  template:
    spec:
      containers:
        - name: opd-service-app
          image: dev-sha-cafe682eb59388e1cace451c8146360ecf690912