replicaCount: 1

image:
  repository: somnathbm/hospital-hms-billing-service
  tag: latest

nameOverride:
  app: billing-app
  svc: billing-svc

service:
  ports:
    grpc:
      name: grpc
      num: 50052
    http:
      name: http
      num: 8000