  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  namespace: hospital-dev

  resources:
    - namespace.yaml
    - opd-service.yaml
    - billing-service.yaml
    - appointment-service.yaml
