replicaCount: 1

image:
  repository: somnathbm/hospital-hms-appointment-service
  tag: latest

service:
  ports:
    grpc:
      name: grpc
      num: 50052
    http:
      name: http
      num: 8000