apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opd-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/somnathbm/hospital-hms-infra.git
    targetRevision: main
    path: overlays/dev/opd-service
  destination:
    server: https://kubernetes.default.svc
    namespace: hospital-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true