apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hospital-hms-service-reader
  namespace: hospital-hms-dev

subjects:
- kind: User
  name: some-user
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io