apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: hospital-hms-dev
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "replicasets", "secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
  