apiVersion: v1
kind: Service
metadata:
  name: {{ include "appointment-service.fullname" . }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "appointment-service.selectorLabels" . | nindent 4 }}
  
  ports:
  - name: grpc
    port: {{ .Values.service.grpcPort }}
    targetPort: {{ .Values.service.grpcPort }}
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}