apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointment-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/somnathbm/hospital-hms-infra.git
    targetRevision: main
    path: kustomize/overlays/dev
    helm:
      valueFiles:
        - appointment-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hospital-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true