apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service-deploy
spec:
  template:
    spec:
      containers:
        - name: billing-service-app
          image: dev-sha-f461bad5bf5b9aa44b86bd1dce33b90811599aa1